---
- name: Install base python deps
  apt:
    name: ['python', 'python3-psycopg2', 'python3-pip', 'python3-dev', 'python3-tk', 'gfortran', 'libblas-dev', 'liblapack-dev']
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  become_method: sudo

- name: update debian packages
  apt: update_cache=true

- name: install memcached
  apt: name=memcached state=present

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

